name: "FAIRSECO-action-test"
description: "GitHub Action that assesses FAIRness in software"
author: "Utrecht University - Slinger Jansen"
inputs:
    repository:
        required: false
        description: "GitHub Repo running the FAIRSECO action"
        default: ${{ github.repository }}
    myToken:
        required: true
        description: "GitHub Token"
runs:
    using: "node16"
    main: "dist/index.js"
branding:
    color: "green"
    icon: "align-left"
